  export const TYPING_INPUT_VALUE = 'TYPING_INPUT_VALUE'
  export const DEFAULT_CURRENCY_TYPING = 'DEFAULT_CURRENCY_TYPING'
  export const TYPING_CURRENCY_NAME = 'TYPING_CURRENCY_NAME'
  export const CURRENCY_DATA_TYPING = 'CURRENCY_DATA_TYPING'
